site_name: Santos Docs
theme: 
  name: material
  features:
    - content.code.annotate #
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: docs
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search
    - awesome-pages
nav:
  - Home: index.md
  # - SRE Tools: 
  #   - Massive Migrate Resourse Groups Tags: sre_tools/rg_massive_tags.md
  #   - Siigo Costs: sre_tools/siigo_costs.md
  # - Terraform:
  #   - Introduccion: terraform/index.md
  #   - gitflow:
  #       - Introduccion: terraform/gitflow/index.md
  #       - IAC: terraform/gitflow/gitflow-iac.md
  #       - Infraestructure Modules: terraform/gitflow/gitflow-infraestructure-modules.md
  - Labs Kubernetes:
        - Minikube:
            - ... | flat |*/minikube/*.md
        - Azure Kubernetes Service:
            - labs_kubernetes/azure/labs1.md
        - Graphana:
            - labs_kubernetes/helm/graphana_prometheus.md
        # - ... 
#   - ... | labs_kubernetes/*.md
  
  - Celery & Fast API Labs:
        - ... | flat | celeryfastapi/*.md

  - Google Maps Scrapper:
        - GoogleMapsScrapper.md
  - Azure Certifications:
        - AZ 204:
            - Azurecertifications/Az204/index.md
            - Azurecertifications/Az204/1.vms.md
  - Microservices with Docker: cbir_project.md
  - Lists In Haskell: haskell.md
  - Versions a Git Clone: versions.md